apiVersion: v1
kind: Secret
metadata:
  name: price-server-secret
  namespace: price-server
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:password@postgres-service:5432/priceserver"
